# -*- coding: utf-8 -*-
"""Session4_1031.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbMpNslwdJumkhWjSv0e-nUkZzby23tl
"""


def factorial_python(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    elif n == 0:
        return 1
    else:
        fact = 1
        for i in range(1, n + 1):
            fact = fact * i
        return fact

# Get input from the user
try:
    num = int(input("Enter a number: "))
    result = factorial_python(num)
    if isinstance(result, str):
        print(result)
    else:
        print(f"Factorial of {num} = {result}")
except ValueError:
    print("Invalid input. Please enter an integer.")
