# -*- coding: utf-8 -*-
"""Session4_1031.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbMpNslwdJumkhWjSv0e-nUkZzby23tl
"""

#include <stdio.h>

int main() {
    int n, i;
    long long factorial = 1;

    printf("Enter a number: ");
    scanf("%d", &n);

    if (n < 0) {
        printf("Factorial is not defined for negative numbers.");
    } else {
        for (i = 1; i <= n; i++) {
            factorial = factorial * i;
        }

        printf("Factorial of %d = %lld", n, factorial);
    }

    return 0;
}

def factorial_python(n):
    if n < 0:
        return "Factorial is not defined for negative numbers."
    elif n == 0:
        return 1
    else:
        fact = 1
        for i in range(1, n + 1):
            fact = fact * i
        return fact

# Get input from the user
try:
    num = int(input("Enter a number: "))
    result = factorial_python(num)
    if isinstance(result, str):
        print(result)
    else:
        print(f"Factorial of {num} = {result}")
except ValueError:
    print("Invalid input. Please enter an integer.")

#include <stdio.h>

int main() {
    int n, a = 0, b = 1, next;

    printf("Enter the number of terms: ");
    scanf("%d", &n);

    printf("Fibonacci Series: ");

    for (int i = 1; i <= n; i++) {
        printf("%d ", a);
        next = a + b;
        a = b;
        b = next;
    }

    return 0;
}

def fibonacci_series_python(n_terms):
    a, b = 0, 1
    series = []
    if n_terms <= 0:
        return []
    elif n_terms == 1:
        return [a]
    else:
        for _ in range(n_terms):
            series.append(a)
            next_term = a + b
            a = b
            b = next_term
        return series

# Get input from the user
try:
    num_terms = int(input("Enter the number of terms: "))
    fib_series = fibonacci_series_python(num_terms)
    if fib_series:
        print("Fibonacci Series:", *fib_series)
    elif num_terms == 0:
        print("Fibonacci Series: (No terms requested)")
    else:
        print("Invalid input. Please enter a positive integer.")
except ValueError:
    print("Invalid input. Please enter an integer.")

#include <stdio.h>

struct Student
{
    int roll_no;
    char name[50];
    float marks;
};

int main()
{
    struct Student s = {101, "Ram", 98};

    printf("--- Student Details ---\n");
    printf("Roll Number: %d\n", s.roll_no);
    printf("Name: %s\n", s.name);
    printf("Marks: %.2f\n", s.marks);

    return 0;
}

class Student:
    def __init__(self, roll_no, name, marks):
        self.roll_no = roll_no
        self.name = name
        self.marks = marks

# Create an instance of the Student class
s = Student(101, "Ram", 98.0)

print("--- Student Details ---")
print(f"Roll Number: {s.roll_no}")
print(f"Name: {s.name}")
print(f"Marks: {s.marks:.2f}")